apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicebusbinding
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString
    value: "" # Replace with actual connection string for local testing
  - name: queueName
    value: "cnammessage"
  - name: route
    value: "/servicebus"
